import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import fs from 'fs';
import path from 'path';

/**
 * 🛠️ Recursive Documizer Sidebar
 * 
 * This configuration automatically scans the /docs directory and builds
 * the sidebar based on your folders. ANY new folder you add will 
 * automatically appear here.
 */

const docsDir = path.join(__dirname, 'docs');
const ignore = ['handbook'];

function getDynamicCategories() {
  if (!fs.existsSync(docsDir)) return [];

  return fs.readdirSync(docsDir)
    .filter(item => {
      const fullPath = path.join(docsDir, item);
      return fs.lstatSync(fullPath).isDirectory() && !ignore.includes(item);
    })
    .map(folder => {
      const categoryPath = path.join(docsDir, folder, '_category_.json');
      let label = folder.charAt(0).toUpperCase() + folder.slice(1);
      let position = 99;

      if (fs.existsSync(categoryPath)) {
        try {
          const config = JSON.parse(fs.readFileSync(categoryPath, 'utf8'));
          label = config.label || label;
          position = config.position || position;
        } catch (e) {}
      }

      return {
        type: 'category' as const,
        label,
        position, // Keep for sorting, strip later
        items: [{ type: 'autogenerated' as const, dirName: folder }],
      };
    })
    .sort((a, b) => a.position - b.position)
    .map(({ position, ...rest }) => rest); // ⬅️ STRIP position before returning to Docusaurus
}

const sidebars: SidebarsConfig = {
  defaultSidebar: [
    {
      type: 'doc',
      id: 'handbook/index',
      label: '👋 Welcome',
    },
    ...getDynamicCategories(),
  ],
};

export default sidebars;
